englconti/MANI

app/controllers/answers_controller.rb
app/controllers/users_controller.rb
app/views/answers/create.html.erb
app/views/answers/update.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/answers_controller_test.rb
test/controllers/users_controller_test.rb

1. users controller created with SHOW method
2. answers controller created with CREATE and UPDATE method

users-&-answers-controller-created

---

app/controllers/lessons_controller.rb
config/routes.rb
test/controllers/lessons_controller_test.rb

1. Added the lessons controller 
2. Changed the routes nesting answers 'create' inside the questions resources

Lessons controller + Routes

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/javascript/packs/application.js
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/initializers/devise.rb
config/routes.rb
package.json
yarn.lock

1. Log-in and Sign-up working
2. Added flatpickr for birthday input when creating new user accounts
3. set username as main login parameter instead of email.

log-in-&-sign-up-working-flatpickr-installed-for-birthday-input

---

Gemfile.lock
app/controllers/products_controller.rb
app/views/products/index.html.erb
app/views/products/products.js
config/routes.rb
test/controllers/products_controller_test.rb

Products controller created + view do index

products created

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/shared/_navbar.html.erb

1. Improvement interface login, edit and new user registration
2. Navbar buttons working

navbar-&-user-edit-new-log-view-improved

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_question.scss
app/controllers/questions_controller.rb
app/models/lesson.rb
app/models/question.rb
app/views/questions/show.html.erb

1. Edited the relations inside the lessons model
2. Created the show method
3. Began the styling of the questions view show

Questions controller - lessons relations

---

Gemfile.lock
app/views/products/show.html.erb
db/migrate/20220607214707_change_column_how_to_invest_name_on_products.rb
db/schema.rb
db/seeds.rb

fixing tuesday merge

---

db/seeds.rb

1. Seed file created to populate Users, Lessons, Questions, Answers and Products.
2. Answers are being created for one single user. Check the seed.rb file for more details.
3. Its recommended to drop your development DB before running this db:seed

First seed file

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Landing Page Almost done
Banner OK
button investments - OK (missing the page to link with the info of the investments)
Cards Investment - Need to work on to align and make it responsive
MISSING
FOOTER

front end landing page almost done

---

app/assets/stylesheets/pages/_user-show-page.scss
app/controllers/answers_controller.rb
app/javascript/controllers/option_card_controller.js
app/views/layouts/application.html.erb
app/views/users/show.html.erb

1. Lesson buttons take user to lesson questions
2. Improvement on conditions

user-page-buttons-upgraded

---

app/assets/stylesheets/components/_question.scss
app/controllers/answers_controller.rb
app/controllers/questions_controller.rb
app/javascript/controllers/next_question_controller.js
app/javascript/controllers/option_card_controller.js
app/javascript/packs/application.js
app/views/questions/show.html.erb
app/views/users/show.html.erb
config/webpack/environment.js
db/seeds.rb

1. Method for submitting user answers to server controller (HTTP request PATCH, "JavaScript(client) to Rails(server)";
2. Logic for answers
3. Seed file corrected for populating correct_answers in Questions

client-to-server-added-for-questions

---

app/controllers/answers_controller.rb
app/controllers/questions_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb
db/seeds.rb

1. Fixed bugs with correct_answers
2. Added logic to update user answers

fixed-bugs-with-lessons-&-logic-for-saving-answers

---

app/assets/stylesheets/components/_question.scss
app/javascript/controllers/next_question_controller.js
app/javascript/controllers/option_card_controller.js
app/views/questions/show.html.erb

1. Changed the confirm button functionality to afterclick make the other options unclickable 
2. Hid the confirm button

Question button + functionalities

---

app/controllers/users_controller.rb
app/javascript/controllers/next_question_controller.js
app/views/layouts/application.html.erb
db/seeds.rb

1. Fixed URL for local host
2. Seed file changed for first lesson with "real" questions

local-host-URL

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_allpages.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_user-show-page.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/users/_lesson.html.erb
app/views/users/show.html.erb

1. Set a entire background-color for all pages and navbar (gradient-lightblue-kinda)
2. Upgrade on User-page-visual
3. Fixed flex-box issue with user page

upgrade-on-user-page

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_user-show-page.scss
app/views/users/_friends-box.html.erb
app/views/users/show.html.erb

1. Improvement on layout e responsivity for User page

improvements-on-user-page-front-end

---

app/controllers/application_controller.rb
app/controllers/questions_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

1. Removed navbar on question page
2. New user account enabled - Answers are populated right after new sign up

new users feature implemented and removed navbar for questions

---

app/assets/stylesheets/components/_question.scss
app/controllers/answers_controller.rb
app/javascript/controllers/next_question_controller.js
app/javascript/controllers/option_card_controller.js
app/views/products/index.html.erb
app/views/questions/show.html.erb
db/schema.rb

1. Displaying the results of the challenge after confirming selection
2. Disabled the confirm button if no option selected 
3. Created style if answer is correct
4. Fixed LCB -> LCA on the products show page

Questions page + LCB->LCA

---

app/assets/stylesheets/pages/_product.scss
app/controllers/pages_controller.rb
app/views/pages/home.html.erb
app/views/products/index.html.erb

pillars-added

---

app/assets/stylesheets/components/_question.scss
app/controllers/questions_controller.rb
app/views/products/index.html.erb
app/views/questions/show.html.erb
app/views/shared/_navbar.html.erb

1. Added advancement bar to question show page

advance-bar-added-to-questions-show-page

---

app/assets/stylesheets/components/_question.scss
app/assets/stylesheets/pages/_user-show-page.scss
app/javascript/controllers/next_question_controller.js
app/javascript/controllers/option_card_controller.js
app/javascript/packs/application.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/questions/show.html.erb
app/views/users/_friends-box.html.erb
app/views/users/show.html.erb
package.json
yarn.lock

1. Added animation for user page and questions page
2. installed animate.css -> $ yarn add animate.css 
3. Refactored markCard function on js controller

Animate & refactoring questions

---

app/assets/stylesheets/components/_question.scss
app/controllers/questions_controller.rb
app/javascript/controllers/hello_controller.js
app/javascript/controllers/next_question_controller.js
app/javascript/controllers/option_card_controller.js
app/views/questions/show.html.erb

1. Improved front-end on question page
2. Logic for loading bar status on questions improved -> Now it moves when user confirms answer

questions-page-upgraded-&-bar-logic

---

app/assets/stylesheets/components/_question.scss
app/assets/stylesheets/pages/_user-show-page.scss
app/controllers/lessons_controller.rb
app/javascript/controllers/option_card_controller.js
app/views/lessons/show.html.erb
config/routes.rb

1. added lesson page
2. border to user page buttons

added-lesson-page

---

app/assets/stylesheets/components/_question.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_lesson-show-page.scss
app/assets/stylesheets/pages/_progress_circle_bars.scss
app/controllers/lessons_controller.rb
app/javascript/controllers/next_question_controller.js
app/views/lessons/_progress-circle-bars.html.erb
app/views/lessons/show.html.erb
app/views/questions/show.html.erb

1. Back-end done for Lesson-show-page
2.  Added some front-end and circle progress bar
3. logic for question buttons working

lesson-page-back-end-done

---

app/assets/stylesheets/pages/_lesson-show-page.scss
app/assets/stylesheets/pages/_progress_circle_bars.scss
app/views/lessons/_progress-circle-bars.html.erb
app/views/lessons/show.html.erb
app/views/questions/show.html.erb

1. Front end done for Lesson Page
2. Changed some english names to portugues (e.g. Questions buttons)

lesson-page-front-end-done

---

app/views/pages/home.html.erb

there was a "</" missplace on line 88 at home.html.erb

fix home page

---

app/controllers/lessons_controller.rb
app/models/lesson.rb
app/views/lessons/show.html.erb
db/data/lessons_starter.csv
db/data/products_starter.csv
db/data/questions_starter.csv
db/migrate/20220613135303_remove_num_of_questions_from_lessons.rb
db/schema.rb
db/seeds.rb
db/seeds_OLD.txt

1. Added CSV reader on seed.file to populate LESSONS, QUESTIONS and PRODUCTS
2. Migration on lessons table removing num_of_questions (it was useless)
3. Validation on seeds.rb before creating new lessons, questions and products
4. added on lesson.rb -> lesson has_many :answers, through: :questions

csv-reader-&-migration-for-lessons

---

app/assets/stylesheets/components/_question.scss
app/javascript/controllers/next_question_controller.js
app/views/questions/show.html.erb

1. Implemented the correct and incorrect sounds
2. Added the font-awesome 'x' 
3. And added the mute unmute button - still not working properly

Questions show page

---

app/assets/stylesheets/pages/_user-show-page.scss
app/controllers/lessons_controller.rb
app/views/lessons/show.html.erb
app/views/users/show.html.erb
db/migrate/20220613194043_add_manis_column_to_users.rb
db/migrate/20220613194515_rename_score_to_xp_in_users.rb
db/schema.rb

1. Users score column renamed to xp
2. Added manis column to Users
3. Implemented xp and manis logic
4. User show page now shows user current xp and manis

xp-&-manis-logic

---

app/assets/stylesheets/components/_question.scss
app/controllers/answers_controller.rb
app/controllers/questions_controller.rb
app/controllers/users_controller.rb
app/javascript/controllers/next_question_controller.js
app/views/lessons/show.html.erb
app/views/questions/show.html.erb
app/views/users/show.html.erb

1. Implemented heart counter feature
2. If user loses all hearts during lesson he will need to go straight to lesson review page

Adding hearts to question page

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_user-show-page.scss
app/controllers/application_controller.rb
app/controllers/friendships_controller.rb
app/controllers/users_controller.rb
app/javascript/controllers/friends_actions_controller.js
app/models/friendship.rb
app/models/user.rb
app/views/friendships/create.html.erb
app/views/friendships/destroy.html.erb
app/views/friendships/index.html.erb
app/views/friendships/new.html.erb
app/views/questions/show.html.erb
app/views/users/_friends-box.html.erb
app/views/users/_friends.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20220614135331_create_friendships.rb
db/migrate/20220614140102_add_status_to_friendship.rb
db/schema.rb
test/controllers/friendships_controller_test.rb
test/models/friendship_test.rb

1. Added window to search for friends and now its possible to add friends
2. NEED to set some rules and conditions still
3. BETA test

Friendships

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_product-show.scss
app/views/pages/home.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

Butao pra voltar no show do products + mudança de imagens

small changes

---

app/assets/stylesheets/pages/_user-show-page.scss
app/controllers/friendships_controller.rb
app/controllers/users_controller.rb
app/views/users/_friends-box.html.erb
app/views/users/_friends.html.erb

1. Its now possible to search for friends and follow/unfollow them
2. current_user is not shown on search
3. followed users XP is shown on friends list
4. scroll bar added for friends list
5. Next step: added Followers and Following count on user page****

friendship working

---

app/assets/stylesheets/components/_question.scss
app/controllers/questions_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/javascript/controllers/wr_choice_controller.js
app/views/questions/_abcd.html.erb
app/views/questions/_writing.html.erb
app/views/questions/show.html.erb

1. Created the writing questions page 
2. Changed the questions controller 
3. Created the writing questions js controller with a method to select each option from the user 
4. Created a partial of the 'abcd' and the writing questions. 
5. To-do: move the footer also into the partials because each of them will need a different confirm button

Questions page!

---

app/views/pages/home.html.erb

foto upload

---

app/javascript/controllers/next_question_controller.js
app/javascript/controllers/option_card_controller.js
app/javascript/controllers/wr_next_question_controller.js
app/javascript/controllers/wr_select_controller.js

1. Refactored and Clean JS controllers

reviewed-and-refactored-js-controllers

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_user-show-page.scss
app/controllers/users_controller.rb
app/javascript/controllers/friends_actions_controller.js
app/javascript/controllers/next_question_controller.js
app/javascript/controllers/wr_next_question_controller.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/users/_friends-box.html.erb

1. Front-end for sending invitation

send-email-front

---

app/javascript/controllers/next_question_controller.js
app/javascript/controllers/wr_next_question_controller.js
app/views/questions/show.html.erb

1. Found some bugs on heroku that dont happen on Local Host. (Some questions do not update and hearts are not working)
2. Changed dataset references from question show HTML to JS.

Fixing heroku bugs try one

---

app/views/users/_friends-box.html.erb
app/views/users/_send-invite.html.erb

1. Partial created for Sending Invites Box
2. Changed the message on the box

partial for invite friends and new message

---

Gemfile
config/initializers/cors.rb

1. Added gem 'rack-cors' and cors.rb at the initializers folder under config

testing-cors-on-heroku
